<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ManualLspClient.Backend</RootNamespace>
    <OutputType>Exe</OutputType>
    <AssemblyName>lspeek-backend</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Client.Core\Client.Core.csproj" />
    <ProjectReference Include="..\Client.Protocol\Client.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="WebUi\index.html" />
  </ItemGroup>

</Project>
